### ISSUE TITLE
prevent form submit when pressing enter in newsletter email field

### ISSUE THREAD

**Issue by julianschnee42** [maxbogo/maxbogo.github.io#18]
**Describe the bug**
When you press enter in the email field of the newsletter form, the form is submitted, refreshing the page instead of showing the popup.

**To Reproduce**
Enter something in the newsletter form and press enter.

**Expected behavior**
The popup is supposed to show up instead of the site reloading

**Comment by Rum3n** [comment]
The new merge fixed the bug but created a new one 

**Describe the bug**
The first time you go on the website and enter your email address the popup only appears for a split second. Afterwards it works normally.

**To Reproduce**
Steps to reproduce the behavior:
Go to https://maxbogo.github.io and type in anything into the 'Enter email' text input and click enter on your keyboard.

**Expected behavior**
The popup should stay up for a longer period of time

**Comment by julianschnee42** [comment]
I added event.preventDefault() which fixed the issue. Closing this now
